import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import '../models/stackchain_config.dart';
import '../presets/preset_registry.dart';

/// Persisted stack snapshot under `.stackchain/lock.yaml`.
class StackLock {
  StackLock({
    required this.packageVersion,
    required this.fingerprint,
    required this.architecture,
    required this.stateManagement,
    required this.routing,
    required this.di,
    required this.network,
    required this.features,
    required this.updatedAt,
  });

  final String packageVersion;
  final String fingerprint;
  final String architecture;
  final String stateManagement;
  final String routing;
  final String di;
  final String network;
  final List<String> features;
  final String updatedAt;

  static const relativePath = '.stackchain/lock.yaml';

  static String pathFor(String root) => p.join(root, relativePath);

  factory StackLock.fromConfig(
    StackchainConfig config, {
    required String packageVersion,
  }) {
    return StackLock(
      packageVersion: packageVersion,
      fingerprint: config.stackFingerprint(),
      architecture: config.architecture.yaml,
      stateManagement: config.stateManagement.yaml,
      routing: config.routing.yaml,
      di: config.di.yaml,
      network: config.network.yaml,
      features: List.of(config.features),
      updatedAt: DateTime.now().toUtc().toIso8601String(),
    );
  }

  factory StackLock.fromYaml(String content) {
    final loaded = loadYaml(content);
    if (loaded is! YamlMap) {
      throw const FormatException('Invalid .stackchain/lock.yaml');
    }
    final featuresRaw = loaded['features'];
    return StackLock(
      packageVersion: '${loaded['package_version'] ?? '0.0.0'}',
      fingerprint: '${loaded['fingerprint'] ?? ''}',
      architecture: '${loaded['architecture'] ?? ''}',
      stateManagement: '${loaded['state_management'] ?? ''}',
      routing: '${loaded['routing'] ?? ''}',
      di: '${loaded['di'] ?? ''}',
      network: '${loaded['network'] ?? ''}',
      features: featuresRaw is YamlList
          ? featuresRaw.map((e) => '$e').toList()
          : const [],
      updatedAt: '${loaded['updated_at'] ?? ''}',
    );
  }

  String toYaml() {
    final feats = features.map((f) => '  - $f').join('\n');
    return '''
# Generated by stackchain — do not edit by hand.
# Tracks the last applied stack so upgrade / migrate can evolve the project.
package_version: "$packageVersion"
fingerprint: "$fingerprint"
architecture: $architecture
state_management: $stateManagement
routing: $routing
di: $di
network: $network
updated_at: "$updatedAt"
features:
$feats
''';
  }

  static Future<StackLock?> read(String root) async {
    final file = File(pathFor(root));
    if (!await file.exists()) return null;
    return StackLock.fromYaml(await file.readAsString());
  }

  static Future<void> write(
    String root,
    StackchainConfig config, {
    required String packageVersion,
  }) async {
    final file = File(pathFor(root));
    await file.parent.create(recursive: true);
    final lock = StackLock.fromConfig(
      config,
      packageVersion: packageVersion,
    );
    await file.writeAsString(lock.toYaml());
  }
}
